{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gatekeeper-policy-manager.serviceAccountName" . }}
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gatekeeper-policy-manager.serviceAccountName" . }}-clstr-role
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ["constraints.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["templates.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["config.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gatekeeper-policy-manager.serviceAccountName" . }}-clstr-role-binding
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gatekeeper-policy-manager.serviceAccountName" . }}-clstr-role
subjects:
- kind: ServiceAccount
  name: {{ include "gatekeeper-policy-manager.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
{{- end }}
